### ISSUE TITLE
Query: How to create a string field which only takes specific values

### ISSUE THREAD

**Issue by abhirakshit** [bypatryk/firestore-schema-validator#1]
Hello,

Can you please tell me how to create a string field which should only take specific string inputs.
e.g
```
status: field('Status')
    .string()
    .trim()
    .allowedValues(["active", "inactive", "closed"])
,
```

What is the best way to achieve this?

Thanks in advance

**Comment by bypatryk** [comment]
Hey @abhirakshit,

You can do it using `oneOf`, like that:

```
status: field('Status')
  .tirm()
  .oneOf([
    'active',
    'inactive',
    'closed',
  ])
```
