### ISSUE TITLE
Unique and Updatable

### ISSUE THREAD

**Issue by eliavco** [bypatryk/firestore-schema-validator#10]
Dear author of this package, your package is absolutely great and in fact, does remind me of Mongoose (which is a great compliment of course). However, there is still a long way to go.
What I suggest you as a first step is to add two methods to the Field object:

1. **Check if a field exists already**, I'll give you an example:
`email: field('Email Adress')
.unique() // Checks if a document with the same field value exists already and if yes, throws error with message 'This Email Address already exists'
.string()
.trim()
.email()`
2. **Check if a field is updatable**, I'll give you an example:
`email: field('Email Adress')
.unupdatable() // Attempts to update this field would be ignored by the schema.
.string()
.trim()
.email()`
the reason why such a thing would be useful is for example if every user has a role that restricts them from accessing certain parts of the app. I don't want people to be able to change their roles after their users have been created. What I could do is to simply filter out the role property from the HTTP request body but I would prefer to just be able to cast the body as is to the document and be assured that the role hasn't changed.
You could even have passwordlike strings to update a field
`email: field('Email Adress')
.unupdatable('secretTwo')
.string()
.trim()
.email()
name: field('Email Adress')
.unupdatable('secretOne')
.string()
.trim()`

`document.save(['secretOne']) // Only the fields whose passwords are contained in the array would be updated`

I would love to hear your feedback.

**Comment by bypatryk** [comment]
Hey @eliavco! Thanks for feedback.

1. `Field.prototype.unique` was on my TODO list. I'll try to implement it ASAP, as I agree it's a core functionality.
2. Adding `Filed.prototype.immutable` (_unupdatable_ is a tongue twister, while _immutable_ is a term well known in the programming world), which allows the field to be set only during creation sounds reasonable.  Not sure if I understand the examples, though. But sounds like a job for `Model.prototype.prehook`. Take a look at the end of the code in [Schema & Model - Robust example](https://github.com/bypatryk/firestore-schema-validator#schema--model---robust-example) section.

I'm open to further discussion.

Also, feel free to submit a PR with any of those functionalities. :)

**Comment by eliavco** [comment]
I was glad to help, and you're absolutely right, immutable is way better than unupdatable.
If I'll find the time I'll try to try to fork this repo. In the meantime, I implemented unique manually.
First, I tried to do that using a custom validator, but I only have access to the value and not to the field name or the model to perform queries.
Then, I Implemented this using prehooks which seems to work perfectly.
`const uniqueFields: [string?] = ['model', 'color', 'price'];`
`uniqueFields.forEach(uniqueField => {`
`	BikeModel.prehook(uniqueField, async (data: any, bike: BikeModel) => {`
`		const result = await checkExists(uniqueField!, data[uniqueField!]);`
`		if (result) throw new ValidationError(`A doucment with that ${uniqueField}: ${data[uniqueField!]} already exists`);})});`
// It's all in typescript

What I think is that this iterator and prehook can be run by default after creating a model, and the array uniqueFields could be a property of the schema, then somehow (this is the part I'm still not sure about), when you call the validator unique it registers the field in the array uniqueFields.
Tell me if that makes any sense, I hope I understood your code well enough.

**Comment by bypatryk** [comment]
Yes, defining the unique keys in Model would be the easy way to implement it.

```js
class UserModel extends Model {
  static get _collectionPath() {
    return 'users'
  }

  static get _schema() {
    return userSchema
  }

  static get _uniqueKeys() {
    return [
      'email',
    ]
  }
}
```

There're some general concerns, like:
1. Which of the (data types)[https://firebase.google.com/docs/firestore/manage-data/data-types] should be allowed to be unique?
Comparing _Array_s and _Map_s (objects) is a dull idea for sure. _Boolean_s can't be really unique. Not sure about _Date and time_s, _Floating-point number_s _Integer_ s, but for sure it makes sense to store unique _Text string_s (eg. email address). It also probably makes sense for _Geographical point_s (eg. unique locations), _ Reference_s (eg. each Player has unique document in Resources collection).

I'm not sure if unique belongs to Model, or maybe rather to Field. So I'm thinking about a more mongoose-like solution, where `unique()` would be a method of `Field` class:

```js
const userSchema = schema({
  email: field('Email')
    .unique()
    .email()
    .trim(),
  firstName: field('First Name')
    .string()
    .trim(),
  lastName: field('Last Name')
    .string()
    .trim(),
})
```

But on the other hand, schemas can be nested, which complicates things a little bit – taking the general concerns into consideration. Eg.:
```js
const companySchema = schema({
  name: field('Name')
    .string()
    .trim(),
  employees: field('Employees')
    .arrayOf(userSchema),
})
```

I need some time to digest this. Happy to hear your thoughts.
