### ISSUE TITLE
Custom filters

### ISSUE THREAD

**Issue by gsouf** [bypatryk/firestore-schema-validator#11]
Hi,

I see from the readme various filters like trim, email, etc... Doc doesn't say anything I could find about it. 

How could I implement custom filters to transform data with my own logic?

Thanks

**Comment by bypatryk** [comment]
Hey @gsouf!

Field instance has `custom(filter)` method, where you can pass your own filters.

Filter must return a function, which takes `value` as an argument and validates it. See [/lib/filters](https://github.com/bypatryk/firestore-schema-validator/blob/master/lib/filters.js) for examples.

**Comment by gsouf** [comment]
Thank you
