### ISSUE TITLE
How to validate models *before* create/update

### ISSUE THREAD

**Issue by kiptoomm** [bypatryk/firestore-schema-validator#13]
Hi @bypatryk, this looks like a very interesting library. I was wondering how one can use it to validate the fields of a model _before_ a write event when requests are coming from the Firebase client SDKs? I can imagine how to do so when requests are coming in from a REST API call (let's say, if we expose an endpoint using Express or using HTTP cloud functions) like so:

    exports.createUser = functions.https.onRequest(async (request, response) => {
        const user = await User.create({
        firstName: request.query.firstName,
        lastName: request.query.LastName,
        email: request.query.emailAddress,
        password: request.query.password,
        birthDate: request.query.dateOfBirth,
        }) // => instance of UserModel
    
        response.json(user.toJSON())
    }

However, I don't know how to take advantage of this library yet because my client apps use the Firebase SDK, which write directly to the document (in other words, how to 'intercept' those requests and validate them through firestore-schema-validator). Would greatly appreciate any examples

**Comment by bypatryk** [comment]
Hey @kiptoomm. This library was designed for NodeJS back-end and currently works only with Cloud Functions.

To validate data before write event you can run `await user.validate()`.

**Comment by kiptoomm** [comment]
> Hey @kiptoomm. This library was designed for NodeJS back-end and currently works only with Cloud Functions.
> 
> To validate data before write event you can run `await user.validate()`.

It's nice to hear that there's a Model `validate()` function (by the way, where's the full docs on all the available methods?). Indeed, I already have a NodeJS back-end and I'm hoping to use this library there, in conjunction with Cloud Functions

However, I'm still not clear on _where_ to run `await user.validate()` **before the write event** - official docs on firestore [function triggers](https://firebase.google.com/docs/firestore/extend-with-functions) only talk about handlers that trigger _after_ a document is written, not _before_

By the way, this other [thread](https://groups.google.com/forum/#!topic/firebase-talk/c5DwcQJb4F4) exactly describes my dilemma

**Comment by bypatryk** [comment]
There's no neat native support for such thing in Firebase, that's why I've created this package. Though, this package was designed for cases when you create REST API with Cloud Functions and your app communicates with Firebase only (or mostly) via this REST API.

What you're probably looking for is [Cloud Firestore Security Rules](https://firebase.google.com/docs/firestore/security/rules-conditions). Eg.:
```
service cloud.firestore {
  match /databases/{database}/documents {
    // Make sure all cities have a positive population and
    // the name is not changed
    match /cities/{city} {
      allow update: if request.resource.data.population > 0
                    && request.resource.data.name == resource.data.name;
    }
  }
}
```

**Comment by kiptoomm** [comment]
> There's no neat native support for such thing in Firebase, that's why I've created this package. Though, this package was designed for cases when you create REST API with Cloud Functions and your app communicates with Firebase only (or mostly) via this REST API.
> 
> What you're probably looking for is [Cloud Firestore Security Rules](https://firebase.google.com/docs/firestore/security/rules-conditions). Eg.:
> 
> ```
> service cloud.firestore {
>   match /databases/{database}/documents {
>     // Make sure all cities have a positive population and
>     // the name is not changed
>     match /cities/{city} {
>       allow update: if request.resource.data.population > 0
>                     && request.resource.data.name == resource.data.name;
>     }
>   }
> }
> ```

Yeah I thought so. It's kind of a pain to use security rules because:
1. It seems to lack granular responses (instead of returning validation errors on specific fields, they just return a blanket `PERMISSION DENIED` error so it's hard to debug and do any additional data manipulation). Most importantly, I'm not able to tell my users which specific form fields failed validation (I'd have to also do client-side validation everywhere, which is OK but it's a bit redundant)
2. The syntax is a bit verbose IMO - having to do `request.resource.data.population` just to get the field is not ideal really

I hope they will introduce `before{Get,Write}` triggers soon so we can use your neat library!
