### ISSUE TITLE
Use schema for form validation on client

### ISSUE THREAD

**Issue by SharadKumar** [bypatryk/firestore-schema-validator#15]
Hi @bypatryk - this lib is slick!

I am wondering if we can suitably use it on the client to validate forms (schema)? I'd like to use it with `react-hook-form` instead of `Yup` or `Joi`. Just to avoid the duplication. How about simple validators like `required` where the must be a value for a prop.

Looked at the Docs and filter.js.

**Comment by SharadKumar** [comment]
Aargh!

```
./node_modules/firestore-schema-validator/lib/Model.js
Module not found: Can't resolve 'firebase-admin' in '/Users/abc/Code/xyz/my/node_modules/firestore-schema-validator/lib'
```

So this lib must be used server-side. I think we should make it upfront on the ReadMe.

**Comment by praneybehl** [comment]
@SharadKumar Please be respectful for the author of the package. Open-source software doesn't mean you own the right to demand of the author/maintainers.
If you would have read the source, it is pretty obvious that the library could not be used for client-side javascript.

**Comment by bypatryk** [comment]
It's kinda stated in [Installation](https://github.com/bypatryk/firestore-schema-validator/blob/master/README.md#installation) section of README. I'm working on a proper/robust documentation for this package. I'll keep it in mind to make it more verbose that it works with NodeJS only.
