### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by AdamMomen** [bypatryk/firestore-schema-validator#21]
Hi bypatryk!

Very helpful package thanks for sharing, 

I would like to know if you are planning to add types for modules? If so, I would love to contribute.

**Comment by bypatryk** [comment]
Hi @AdamMomen! Thanks, I'm happy you like it!

Yes, rewriting codebase to TS is definitely in the roadmap, so feel free to contribute with a Pull Request. 😄
