### ISSUE TITLE
Front end support

### ISSUE THREAD

**Issue by bscp** [bypatryk/firestore-schema-validator#29]
It would be nice if this framework could be used in the front-end. The current way of getting the Firestore object through `firebase-admin` ([here](https://github.com/bypatryk/firestore-schema-validator/blob/6a5d875e77821f95145d5ad44f775cdbffacea74/lib/Model.js#L31) & [here](https://github.com/bypatryk/firestore-schema-validator/blob/6a5d875e77821f95145d5ad44f775cdbffacea74/lib/Model.js#L124)) eliminates that possibility. I would be happy to submit a pull request.

**Comment by bypatryk** [comment]
I am happy to review your pull request and release it :)
