### ISSUE TITLE
email method and message

### ISSUE THREAD

**Issue by JSsantana** [bypatryk/firestore-schema-validator#30]
Where the .email() comes from? How to change the error messages?

**Comment by bypatryk** [comment]
@JSsantana Email uses this regex: https://github.com/bypatryk/firestore-schema-validator/blob/master/lib/filters.js#L73
You can use custom error message by providing errorMessage argument to `.email(errorMessage)` - https://github.com/bypatryk/firestore-schema-validator/blob/master/lib/filters.js#L71
`%s` will be replaced with field label (name) specified through `.field(label)`
