### ISSUE TITLE
Validate array of enums

### ISSUE THREAD

**Issue by kk2491** [bypatryk/firestore-schema-validator#32]
Hello, 

Thanks for providing the excellent way to validate the schema in this repository. 
I have recently started using it, and need help in validating the below data structure.  

Data to be validated is   

```
{
    userId : "test-user-id",
    task : ["read", "write", "run"]
}
```
The field task is array of enum values which can taken `read`, `write`, `run`, `sleep`, `eat`.  

Schema validation I have come up with is as below:  

```
userInputSchema: schema({
   userId: field("userId").string(),
   task: field("task").arrayof(),  
})
```

How can we specify that the task can take only the predefined enum values?

Thank you,  
KK

**Comment by bypatryk** [comment]
Hey! You can use `oneOf()` to achieve that. Look at the example in README, ie.:
```js
      lang: field('Language')
        .oneOf([
          'en-US',
          'pl-PL'
        ])
        .default('en-US'),
```
