### ISSUE TITLE
Are sub-collections currently supported?

### ISSUE THREAD

**Issue by wprk** [bypatryk/firestore-schema-validator#4]
I'm trying to get your package working with a subcollection. E.g. I have a Venue Model which has a sub-collection of Ratings. How can I go about creating a VenueRating Model?

**Comment by bypatryk** [comment]
Hi @wprk!

Sub-collections are a little bit tricky, but you can definitely manage them. To access Ratings of a Venue, you need to know the ID of the Venue first.

I didn't have a chance to test this code, but it probably should work correctly:

```javascript
const { Model, schema, field } = require('firestore-schema-validator')

const ratingSchema = schema({
  score: field('Score')
    .integer()
    .min(0)
    .max(5)
})

const ratingModelFactory = (venueId) => {
  class RatingModel extends Model {
    static get _collectionPath() {
      return `venue/${venueId}/rating`
    }

    static get _schema() {
      return ratingSchema
    }
  }

  return RatingModel
}

const venueSchema = schema({
  name: field('Name')
    .string()
    .trim(),
})

class Venue extends Model {
  constructor (_snapshot, _data) {
    super(_snapshot, _data)

    this.ratingModel = ratingModelFactory(this._id)
  }
  
  static get _collectionPath() {
    return 'venue';
  }

  static get _schema() {
    return venueSchema;
  }
}
```

And then you can access that RatingModel via VenueModel.

Let me know if that works!

**Comment by wprk** [comment]
That worked perfectly. Thanks alot @bypatryk!
