### ISSUE TITLE
Nested Schema

### ISSUE THREAD

**Issue by DevonFazekas** [bypatryk/firestore-schema-validator#6]
Amazing work, @bypatryk.

In one schema, I have an array of objects. These objects are repeated in other schemas so I'd like to reduce duplicate code by nesting schemas. Is this possible? The documentation isn't clear.

Here's an example JSON that I'm trying to filter through your schemas.

```json
{
"id": "727",
"status": "active",
"lineItems": [
   {
      "name": "Single #1",
      "price": "565"
   }
]
}
```

Here's what I had in mind but the expected argument for `arrayOf()` is of type `field` not `schema`.
```Javascript
const productSchema = schema({
   name: field("Name"),
   price: field("Price")
});

const orderSchema = schema({
   id: field("ID"),
   status: field("Status"),
   line_items: field("Items").arrayOf(productSchema) // This won't work.
});
```

Any suggestions would be amazing!

**Comment by DevonFazekas** [comment]
Apparently, my code works as desired. No issue, only a poor understanding of your definition of a `field`.

**Comment by bypatryk** [comment]
Thanks @DevonFazekas! 

Using `schema` instead of `field` in `arrayOf()` might deliver unexpected results. Instead you can create `productFields` object and use it both in `productSchema` and `orderSchema` like that:

```javascript
const productFields = {
  name: field('Name'),
  price: field('Price'),
}

const productSchema = schema(productFields)

const orderSchema = schema({
  id: field('ID'),
  status: field('Status'),
  line_items: field('Items')
    .arrayOf(productFields),
})
```

**Comment by DevonFazekas** [comment]
@bypatryk , thank you for your quick response! I tried your suggestion but it results in the following error:

![image](https://user-images.githubusercontent.com/54437075/73992208-5dcf4c80-491c-11ea-9ba5-2c50e56a13e1.png)

Here's my approach:
```javascript
const { Model, schema, field } = require("firestore-schema-validator");

const itemFields = {
   name: field("Item Name").string().trim()
};
const billingFields = {
   country: field("Billing Country").string().trim()
};

const orderSchema = schema({
   status: field("Order Status").string().trim(),
   items: field("Order Items").arrayOf(itemFields),
   billing: field("Order Billing").objectOf(billingFields)
});

class OrderModel extends Model {
   static get _collectionPath() {...}
   static get _schema() {
      return orderSchema;
   }
}
module.exports = OrderModel;
```
```javascript
const OrderModel = require("./orderModel");
let itemData = [
   { name: "Item 1" }, 
   { name: "Item 2" }
];
let billingData = {
   country: "Canada"
};
let order = await OrderModel.create({
   status: "Processing", 
   items: itemData,
   billing: billingData
});
```
I'd like to note that the `field("Order Billing").objectOf(billingFields)` field works perfectly, as far as I can tell, and commenting out `field("Order Items").arrayOf(itemFields)` removes the error.

Also, in your suggestion: How does the `productSchema` fit into the `OrderModel` if we're only referencing the `productFields` object? 
I don't think I understand how the flow of validation works. In  my above example, should I still be using `productSchema` or is it not needed for validation?

**Comment by bypatryk** [comment]
@DevonFazekas, sorry for late response this time!

Actually, I made a mistake and your initial approach – using `schema` inside of `field.arrayOf` – was 100% correct.

I'll update documentation and mark that you can use either `field` or `schema`. I'll also make `field.objectOf` accept `schema` as well.

**Edit: Updated!**
