### ISSUE TITLE
Help with references

### ISSUE THREAD

**Issue by ncalderini** [bypatryk/firestore-schema-validator#9]
Hey @bypatryk, great work!

I'm new to Firestore and JS in general so maybe I'm doing something wrong

I have a collection of `items` in Firestore with this schema

``` Javascript
const itemSchema = schema({
  title: field('Title')
    .string()
    .trim(),
  price: field('Price')
    .string()
    .trim(),
  description: field('Description')
    .string()
    .trim(),
  thumbUrl: field('ThumbUrl')
    .string()
    .trim(),
  images: field('Images')
    .array(),
  rating: field('Rating')
    .number(),
  suggestions: field('Suggestions')
    .array() 
});
```

I need help with the suggestions field, I want it to be an array of references to other items. 

When I try to retrieve a document using `Model.getById(id)` with a reference in it I get the following error `TypeError: Converting circular structure to JSON`.

Any suggestions in how to accomplish this?

Thanks!

**Comment by bypatryk** [comment]
Hey @ncalderini, thanks!

I'm trying to analyze what can cause the problem, but I'll need more details.

1. Are you sure that the `TypeError: Converting circular structure to JSON ` error shows up when you're getting the data (`Model.getById(id)`) and now while saving it?

In general the error means that object is referencing itself, eg.:
```js
const a = {}
a.b = a
```
and JSON parser gets into an infinite loop.

2. Can you paste the code which you use for storing the suggestions?

**Comment by ncalderini** [comment]
Thanks for replying @bypatryk. 

For now I created the items directly into the firestore database viewer. I have two mock items and `suggestions` is an array of references.

<img width="1137" alt="Screen Shot 2020-04-22 at 17 42 38" src="https://user-images.githubusercontent.com/19273686/80031887-b7c5c400-84c0-11ea-98ab-11f2828c3b2b.png">

This is my `index.js`

``` Javascript
// The Cloud Functions for Firebase SDK to create Cloud Functions and setup triggers.
const functions = require('firebase-functions');
// The Firebase Admin SDK to access the Firebase Realtime Database.
const admin = require('firebase-admin');

//Express API
const express = require('express');
const bodyParser = require('body-parser');

//Model Imports
const Item = require('./domain/ItemModel');
const Timestamp = admin.firestore.Timestamp;

//Init configuration
admin.initializeApp();

const app = express();
const main = express();

main.use('/api/v1', app);
main.use(bodyParser.json());

//ItemApi --- exposed Methods
exports.webApi = functions.https.onRequest(main);

app.get('/items/:id', async (request, response) => {
  try {
    const item = await Item.getById(request.params.id);
    response.status(200).json(item ? item : {});
  } catch (error) {
    response.status(500).send(error.toString());
  }
});
```

This is my `ItemModel`

```JavaScript
// UserModel.js
const { Model, schema, field } = require('firestore-schema-validator');

const itemSchema = schema({
  title: field('Title')
    .string()
    .trim(),
  price: field('Price')
    .string()
    .trim(),
  description: field('Description')
    .string()
    .trim(),
  thumbUrl: field('ThumbUrl')
    .string()
    .trim(),
  images: field('Images')
    .array(),
  rating: field('Rating')
    .number(),
  suggestions: field('Suggestions')
    .array() 
});

class ItemModel extends Model {

  static get _collectionPath() {
    return 'items'
  }

  static get _schema() {
    return itemSchema
  }
}

module.exports = ItemModel
```

If I delete the `suggestions` field from the item it works like a charm.

Thanks again for the support!

**Comment by bypatryk** [comment]
@ncalderini in Cloud Firestore DB you're storing suggestions as an array of [DocumentReference](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference). Which, when retrieved with Firebase, becomes an instance of DocumentReference. When you try to parse it to JSON, it ends up in some infinite loop.

It took me a while to debug, because when you run it locally (via `firebase emulators:start`), this DocumentReference instance is being JSONified to something like:
```json
{
  "_firestore": {
    "_settings": {
      "projectId": "project-id,
      "firebaseVersion": "8.10.0",
      "libName": "gccl",
      "libVersion": "3.7.4 fire/8.10.0",
      "servicePath": "firestore.googleapis.com",
      "port": 443,
      "clientConfig": {},
      "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/datastore"
      ]
    },
    "_settingsFrozen": true,
    "_serializer": {},
    "_projectId": "project-id",
    "registeredListenersCount": 0,
    "_lastSuccessfulRequest": 1587753814398,
    "_backoffSettings": {
      "initialDelayMs": 100,
      "maxDelayMs": 60000,
      "backoffFactor": 1.3
    },
    "_preferTransactions": false,
    "_clientPool": {
      "concurrentOperationLimit": 100,
      "maxIdleClients": 1,
      "activeClients": {},
      "terminated": false,
      "terminateDeferred": {
        "promise": {}
      }
    }
  },
  "_path": {
    "segments": [
      "items",
      "1yae21CJNBL1FP8LTqkO"
    ]
  },
  "_converter": {}
}
```
but on Firebase server it just throws the `TypeError: Converting circular structure to JSON` error. The JSONified structure probably isn't what you're looking for anyway.

You can define your own `toJSON()` method on `ItemModel` and rework how suggestions are JSONified, eg.:
```js
class ItemModel extends Model {
  // ...

  toJSON() {
    return {
      // fields defined in schema
      ...this._data,

      // suggestions overwritten to simple objects
      suggestions: this.suggestions.map(suggestion => {
        return {
          path: suggestion.path,
          id: suggestion.id,
        }
      }),
    }
  }
}
```
